config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "inventories#index"

  resources :inventories do
    resources :items
  end
  resources :shipments do
    member do
      get 'add_inventory/:shipment_id', to: 'shipments#add_inventory', as: :add_inventory
      post 'add_inventory/:shipment_id', to: 'shipments#add_inventory'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord

  # ASSOCIATIONS
  has_many :items, dependent: :destroy
  belongs_to :shipment, optional: true

  # VALIDATIONS
  validates :name, presence: true
  validates :shipment_id, presence: true, allow_blank: true
end

app/models/item.rb
class Item < ApplicationRecord

  # ASSOCIATIONS
  belongs_to :inventory

  # VALIDATIONS
  validates :name, presence: true
  validates :count, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/shipment.rb
class Shipment < ApplicationRecord

  # ASSOCIATIONS
  has_many :inventories
  has_many :items, through: :inventories

  # VALIDATIONS 
  validates :name, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
  end
  
  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new
    @inventory = Inventory.create(inventory_params)
    if @inventory.save
      flash[:notice] = "New inventory created!"
      redirect_to @inventory
    else
      flash[:alert] = "Try again."
      render :new
    end
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])
    if @inventory.update(inventory_params)
      flash[:notice] = "Inventory updated!"
      redirect_to @inventory
    else
      render :edit
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    flash[:alert] = "Inventory deleted."
    redirect_to root_path, status: :see_other
  end

  private
  def inventory_params
    params.require(:inventory).permit(:name, :shipment_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # CALLBACKS
  before_action :set_inventory#, except: :destroy
  
  def index
    @items = @inventory.items.all
  end

  def new
    @item = @inventory.items.new
  end

  def create
    @item = @inventory.items.new
    @item = @inventory.items.create(item_params)
    if @item.save
      flash[:notice] = "New item created!"
      redirect_to @inventory
    else
      render :new
    end
  end

  def edit
    @item = @inventory.items.find(params[:id])
  end

  def update
    @item = @inventory.items.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "Item updated!"
      redirect_to inventory_path(@inventory)
    else
      render :edit
    end
  end

  # def show
  #   @items = @inventory.items.all
  # end

  def destroy
    @item = @inventory.items.find(params[:id])
    flash[:alert] = "Item deleted." if @item.destroy
    redirect_to @inventory, status: :see_other
  end

  private
  def item_params
    params.require(:item).permit(:name, :count, :inventory_id)
  end

  def set_inventory
    @inventory = Inventory.find(params[:inventory_id])
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController

  # CALLBACKS

  def index
    @shipments = Shipment.all
  end

  def show
    @shipment = Shipment.find(params[:id])
    @inventories = Inventory.all
  end

  def new
    @shipment = Shipment.new
  end

  def create
    @shipment = Shipment.new
    @shipment = Shipment.create(shipment_params)
    if @shipment.save
      flash[:notice] = "New shipment created!"
      redirect_to @shipment
    else
      flash[:alert] = "Please try again."
      render :new
    end
  end

  # def find_inventory
  #   @shipment = Shipment.find(params[:id])
  #   @inventories = Inventory.all
  # end

  def add_inventory
    @shipment = Shipment.find(params[:id])
    @inventory = Inventory.find(params[:shipment_id])
    if @inventory.update_attribute(:shipment_id, @shipment.id)
      flash[:notice] = "Inventory added to shipment!"
      redirect_to shipment_path(@shipment), status: :see_other
    else
      flash[:alert] = "Please try again."
      render :add_inventory
    end
  end

  def edit
    @shipment = Shipment.find(params[:id])
  end

  def update
    @shipment = Shipment.find(params[:id])
    if @shipment.update
      flash[:notice] = "Shipment updated!"
      redirect_to @shipment
    else
      render :edit
    end
  end

  def destroy
    @shipment = Shipment.find(params[:id])
    @shipment.destroy
    flash[:alert] = "Shipment dropped."
    redirect_to root_path
  end

  private
  def shipment_params
    params.require(:shipment).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventories/_form.html.erb
<%= form_with model: @inventory do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div><br>
  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/inventories/edit.html.erb
<h3>Edit the inventory:</h3>
<%= render "form" %>

app/views/inventories/index.html.erb
<div class="container-fluid">
  <% if @inventories.blank? %>
    <br>
    <h3>Click below to create a new Inventory!</h3><br>
    <%= link_to "Create Inventory", new_inventory_path, class: "btn btn-outline-primary" %>
  <% else %>
    </br>
    <h5>LIST OF CURRENT INVENTORIES:</h5>
    <% @inventories.each do |inventory| %>
      <ol>
        <%= link_to "#{inventory.name.upcase}", inventory_path(inventory) %>
      </ol>
    <% end %>
    <br>
    <strong>Click below to create a new Inventory!</strong><br>
    <div><%= link_to "Create Inventory", new_inventory_path, class: "btn btn-outline-primary" %></div>
  <% end %>
</div>

app/views/inventories/new.html.erb
<h3>Create a new inventory:</h3><br>
<%= render "form" %>

app/views/inventories/show.html.erb
<br>
<h3><%= @inventory.name.upcase %></h3>
<span>
  <%= link_to "Delete Inventory", inventory_path(@inventory), 
    data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    }, class: "btn btn-outline-danger" %>
</span><br><br>
<% if @inventory.items.exists? %>
  <strong>Items: </strong><br>
  <%= render @inventory.items %>

  <strong>Add a new item:</strong><br>
  <%= render "items/form" %>
<% else %>
  <h4>Inventory is empty!</h4><br>
  <strong>Add a new item:</strong><br>
  <%= render "items/form" %>
<% end %>

app/views/items/_form.html.erb
<%= form_with model: [ @inventory, @inventory.items.build ] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div><br>
  <div>
    <%= form.label :count %>
    <%= form.number_field :count, min: 0 %>
  </div><br>
  <%= form.hidden_field :inventory_id %>
  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/items/_item.html.erb
<strong>Name:</strong> <%= item.name %><br>
<strong>Count:</strong> <%= item.count %><br>
<span>
  <%= link_to "Update count", edit_inventory_item_path(item.inventory_id, item) %>
  <%= link_to "Remove", inventory_item_path(item.inventory_id, item), 
      data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
      }, class: "text-danger" %>
</span>
<br>

app/views/items/edit.html.erb
<h3>Edit the item:</h3>
<%= form_with model: [@inventory, @item] do |form| %>
  <div>
    <%= form.label :count %>
    <%= form.number_field :count, min: 0 %>
  </div><br>
  <%= form.submit class: "btn btn-dark" %>
<% end %>

app/views/items/new.html.erb
<h3>Add a new item:</h3><br>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="navbar-brand mb-0 h1">Inventory Manager</div>
        <span>
          <div class="container-fluid">
            <%= link_to "Shipments", shipments_path, class: "btn btn-success" %>
            <%= link_to "Go to Home", root_path, class: "btn btn-primary" %>
          </div>
        </span>
      </div>
    </nav>
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div> 
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %> 
    <br>
    <%= yield %>
  </body>
</html>

app/views/shipments/_form.html.erb
<%= form_with model: @shipment do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div><br>
  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/shipments/edit.html.erb
<h3>Edit the shipment:</h3>
<%= render "form" %>

app/views/shipments/index.html.erb
<% if @shipments.blank? %>
<br>
  <h3>No shipments present!</h3><br>
  <strong>Click below to create a new Shipment!</strong><br>
  <%= link_to "Create Shipment", new_shipment_path, class: "btn btn-outline-primary" %>
<% else %>
  </br>
  <h5>LIST OF CURRENT SHIPMENTS:</h5>
  <div class="container-fluid">
    <% @shipments.each do |shipment| %>
      <ol>
        <%= link_to "#{shipment.name.upcase}", shipment_path(shipment) %>
      </ol>
    <% end %>
  </div>
<% end %>

app/views/shipments/new.html.erb
<h3>Create a new shipment:</h3><br>
<%= render "form" %>

app/views/shipments/show.html.erb
<div class="container-fluid">
<%= @shipment.name.upcase %><br>
<% @inventories.each do |inventory| %>
  <h4><%= inventory.name.upcase %></h4>
  <strong>Items:</strong><br>
  <ol>
  <% inventory.items.each do |item| %>
    <li>
      <span>
      <strong>Name:</strong>
      <%= item.name %>
      |
      <strong>Count:</strong>
      <%= item.count %>
      </span>
    </li>
  <% end %>
  </ol>
  <%= link_to "Add to shipment", add_inventory_shipment_path(@shipment, inventory) %>
<% end %>
</div>